/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as interface from "./interface";
export type { interface };
import type * as mocks from "./mocks";
export type { mocks };
export type { AutoExitBot } from "./AutoExitBot";
export type { MockToken } from "./MockToken";
